network:
  version: 2
  renderer: NetworkManager # Can move all to networkd in the future
  ethernets:
    eth0:
      renderer: networkd # Use networkd for this interface
      dhcp4: false # Static IP
      addresses: [192.168.101.111/24] # 8 bits
      mtu: "9000" # High MTU for gige camera communication

