---
- name: Install Telegraf and configure tegrastats
  hosts: '{{ hosts }}'
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_become_password: "ubuntu"
    ansible_python_version: "3.8"
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
  - name: Copy devops directory
    copy:
      src: /home/ubuntu/devops
      dest: /home/ubuntu
      mode: "0755"
    remote_user: ubuntu

  - name: Install moreutils
    apt:
      name: moreutils
      state: present

  - name: Download InfluxDB key
    get_url:
      url: https://repos.influxdata.com/influxdb.key
      dest: /home/ubuntu/influxdb.key

  - name: Add InfluxDB key
    become: true
    shell: |
      echo '23a1c8836f0afc5ed24e0486339d7cc8f6790b83886c4c96995b88a061c5bb5d influxdb.key' | sha256sum -c && \
      cat influxdb.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
    args:
      executable: /bin/bash    
   
  - name: Add InfluxDB repository
    become: true
    become_user: root
    shell: echo 'deb https://repos.influxdata.com/ubuntu focal stable' | sudo tee /etc/apt/sources.list.d/influxdb.list

  - name: Add missing key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: D8FF8E1F7DF8B07E

  - name: Update package cache
    apt:
      update_cache: yes

  - name: Install Telegraf
    apt:
      name: telegraf
      state: present

  - name: Copy logrotate config
    copy:
      src: /home/ubuntu/devops/jetson_stats/logrotate_config/tegrastats
      dest: /etc/logrotate.d/
    become: true

  - name: Copy systemd service
    copy:
      src: /home/ubuntu/devops/jetson_stats/systemd_service/tegrastats.service
      dest: /etc/systemd/system/
    become: true

  - name: Copy Telegraf config
    copy:
      src: /home/ubuntu/devops/jetson_stats/telegraf_config/telegraf.conf
      dest: /etc/telegraf/
    become: true

  - name: Reload systemd
    systemd:
      daemon_reload: yes
    become: true

  - name: Start Telegraf
    systemd:
      name: telegraf
      state: started
    become: true

  - name: Set tegrastats script path
    replace:
      path: /etc/systemd/system/tegrastats.service
      regexp: '<PATH_TO_SCRIPT>'
      replace: '/home/ubuntu/devops/jetson_stats'
    become: true

  - name: Start tegrastats
    systemd:
      name: tegrastats
      state: started
    become: true


