- hosts: local
  become: true
  tasks:
    - name: Login to JFrog Docker registry
      docker_login:
        registry_url: industrialnext.jfrog.io
        username: "svc-artfactory"
        password: "D27z&j62sPLk"

    - name: Pull cv_services image from JFrog Docker registry
      docker_image:
        name: industrialnext.jfrog.io/in-docker/{{ packagename }}
        tag: "{{ version }}"
        source: pull
